package com.vari.clockify.check.domain;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum TagName {
    SALES("SALES"),
    QA("QA"),
    CALL_MEETING("CALL / MEETING"),
    PLANNING("PLANNING"),
    DEVELOPMENT("DEVELOPMENT"),
    CODE_REVIEW("CODE REVIEW"),
    RESEARCH("RESEARCH"),
    LEARNING("LEARNING"),
    DESIGN("DESIGN"),
    REPORTING("REPORTING"),
    DOCUMENTATION("DOCUMENTATION"),
    PROJECT_ADMINISTRATION("PROJECT ADMINISTRATION"),
    ACCOUNT_MANAGEMENT("ACCOUNT MANAGEMENT"),
    MENTORING_ONBOARDING("MENTORING / ONBOARDING"),
    SUPPORT("SUPPORT"),
    HELLOTAX_SUPPORT_CS("HELLOTAX SUPPORT - CS"),
    HELLOTAX_SUPPORT_OP("HELLOTAX SUPPORT - OP"),
    HELLOTAX_SUPPORT_FILING("HELLOTAX SUPPORT - FILING"),;

    private final String name;
}
